### ISSUE TITLE
Blind search

### ISSUE THREAD

**Issue by ma-diroma** [thoree/Familias#2]
Hi,

I would like to use Familias R package. It is not clear to me if the blind search present in the Windows interface version has also been implemented in the command line version.
Thanks.

Best wishes,
Maria Angela

**Comment by thoree** [comment]
Hi
The blind search is unfortunately not available in the Familias R package.
There is however related R software (and much more) in the ped-suite of R
libraries,
on cran and gitHub, developed by Magnus Dehli Vigeland.
For instance, the library forrel on https://github.com/magnusdv/forrel
contains the function checkPairwise.
Best wishes

Thore



fre. 17. jul. 2020 kl. 17:32 skrev Maria Angela Diroma <
notifications@github.com>:

**Comment by ma-diroma** [comment]
Thank you so much for your help.
BW,
Maria Angela
